### ISSUE TITLE
Encountered an error

### ISSUE THREAD

**Issue by deepdreamerzhang** [Fantasy-Studio/Paint-by-Example#10]
Hello, very interesting work! When I ran inference.py, I got Paint-by Example/ldm/models/diffusion/ddim.py", line 150, in ddim_sampling
    img = torch.cat((img, kwargs['rest']), dim=1)
KeyError: 'rest'. Do you have any suggestions about this, thank you!

**Comment by Fantasy-Studio** [comment]
The bug in ddim.py has been solved, you can now also try to use ddim for sampling.
