### ISSUE TITLE
Where the "We utilize 15 fully-connected (FC) layers to decode the feature from pretrained encoder and inject it into the diffusion process through cross attention." in this code?

### ISSUE THREAD

**Issue by zhangquanwei962** [Fantasy-Studio/Paint-by-Example#15]
Thank you for your excellent work!

As above, I don't know where the 15 FC in this code. Can you help me?

**Comment by Fantasy-Studio** [comment]
We appreciate your interest in our work. In the code, the 15 FC layers are introduced in the form of a 5-layer transformer. Since the number of tokens is 1, one transformer is equivalent to 3 FC layers. Thus, a 5-layer transformer is equivalent to 15 FC layers.

**Comment by francotheengineer** [comment]
If there a reason you did this?
Is it because the original stable diffusion expect clip embeddings input in this way? or maybe because you're using a learned embeddings of the reference images?
