### ISSUE TITLE
How to extract the foreground of the reference image before using DCCF?

### ISSUE THREAD

**Issue by Yongssss** [Fantasy-Studio/Paint-by-Example#16]
Thanks for your excellent work.
When reading your paper, I am confused about how to extract the foreground of the reference image before using DCCF. Are these foreground masks generated automatically through LAMA? If so, can you elaborate on how to implement it?

**Comment by Fantasy-Studio** [comment]
We appreciate your interest in our work. 
The foreground masks are manually annotated.
