### ISSUE TITLE
The algorithm of cropping the square image in line 217 of the file open-images.py. 

### ISSUE THREAD

**Issue by Yongssss** [Fantasy-Studio/Paint-by-Example#18]
Thanks for your excellent work.

For $W>H$, the algorithm will not crop the image if the box width is greater than or equal to the image height, and will crop the area around the box if the box width is less than the image height. Do I misunderstand this algorithm?

**Comment by Fantasy-Studio** [comment]
There is "elif" in line 227.
https://github.com/Fantasy-Studio/Paint-by-Example/blob/3d223b66cdee19cde04f9e9b83ff714d18752622/ldm/data/open-images.py#L227
