### ISSUE TITLE
When will the COCOEE be published?

### ISSUE THREAD

**Issue by KleinXin** [Fantasy-Studio/Paint-by-Example#19]
thx!

**Comment by shamitlal** [comment]
Hi Authors,
Thanks for the amazing contribution!
Do you have any update on when COCOEE will be released?

Thanks

**Comment by Fantasy-Studio** [comment]
We appreciate your interest in our work. We have just released the COCOEE dataset.

**Comment by shamitlal** [comment]
Thanks for releasing the COCOEE dataset!
Will you also be releasing the script that can be executed to compute FID-CLIP-QS scores?
