### ISSUE TITLE
Why are bboxes processed only for first 500 images in each directory?

### ISSUE THREAD

**Issue by shamitlal** [Fantasy-Studio/Paint-by-Example#23]
Hi,
Thanks for open sourcing the implementation.
I was going through the read_bbox.py script, and saw that you only process the first 500 images in each directory (train_0, train_1,....)
Link for code: https://github.com/Fantasy-Studio/Paint-by-Example/blob/main/scripts/read_bbox.py#L26

Is there a reason for this? Wouldn't this limit the amount of training data to 16*500 images only?

Thanks
Shamit

**Comment by Fantasy-Studio** [comment]
Sorry, this is a bug left by my testing before making the code public, and it has been fixed.
