### ISSUE TITLE
Generate effect issues when mask size is different

### ISSUE THREAD

**Issue by wzhiyuan2016** [Fantasy-Studio/Paint-by-Example#33]
Hello, I conducted a small experiment: generating mud spots，
The experimental results are as follows due to different mask sizes：
1.
![1](https://github.com/Fantasy-Studio/Paint-by-Example/assets/33740622/10203c28-f444-44c2-9419-1611545e5085)
2.
![2](https://github.com/Fantasy-Studio/Paint-by-Example/assets/33740622/7761a613-1c24-4205-b71e-3e282459e0ed)
3.
![3](https://github.com/Fantasy-Studio/Paint-by-Example/assets/33740622/abdfa001-ee7b-43fe-aab3-717f0490506e)

Problem: 
1. When mask1 to mask2, no effect is generated
2. When using mask3, it seems that it has not taken effect

What is the reason for this

thanks

**Comment by wzhiyuan2016** [comment]
![4](https://github.com/Fantasy-Studio/Paint-by-Example/assets/33740622/51001e08-124f-42ee-bdfb-92cd8d39cfa1)
When I set the mask very low, it didn't take effect

**Comment by Fantasy-Studio** [comment]
The reason for the small mask not being able to generate good results is that the masks used during training are not so small. I believe this can be solved by adding this type of data during training.
As for the results from mask1 to mask2, you can try a larger CFG guidance.

**Comment by wzhiyuan2016** [comment]
> The reason for the small mask not being able to generate good results is that the masks used during training are not so small. I believe this can be solved by adding this type of data during training. As for the results from mask1 to mask2, you can try a larger CFG guidance.

Okay, I'll give it a try，thanks
