### ISSUE TITLE
Web demo is not working

### ISSUE THREAD

**Issue by Jimlee079** [Fantasy-Studio/Paint-by-Example#40]
> ===== Application Startup at 2023-07-08 23:27:50 =====

> The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.
> 
> 0it [00:00, ?it/s]
> 0it [00:00, ?it/s]
> Couldn't connect to the Hub: 500 Server Error: Internal Server Error for url: https://huggingface.co/api/models/Fantasy-Studio/Paint-by-Example (Request ID: Root=1-64a9f0fc-6612745c1d91f5f31284905b)
> 
> Internal Error - We're working hard to fix this as soon as possible!.
> Will try to load from local cache.
> Traceback (most recent call last):
>   File "app.py", line 17, in <module>
>     pipe = DiffusionPipeline.from_pretrained(
>   File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/diffusers/pipelines/pipeline_utils.py", line 882, in from_pretrained
>     cached_folder = cls.download(
>   File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/diffusers/pipelines/pipeline_utils.py", line 1315, in download
>     cached_folder = snapshot_download(
>   File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
>     return fn(*args, **kwargs)
>   File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/huggingface_hub/_snapshot_download.py", line 169, in snapshot_download
>     with open(ref_path) as f:
> FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.cache/huggingface/hub/models--Fantasy-Studio--Paint-by-Example/refs/main'

After I open the web demo, it shows a Runtime error with message above.

**Comment by Fantasy-Studio** [comment]
It's been rebooted.
