### ISSUE TITLE
about environment

### ISSUE THREAD

**Issue by monument-and-sea-all-the-gift** [Fantasy-Studio/Paint-by-Example#5]
git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
it's a no found page
how to solve it
looking forward to your reply，thank you

**Comment by Fantasy-Studio** [comment]
Can you show the full error log？发自我的手机-------- 原始邮件 --------发件人： monument-and-sea-all-the-gift ***@***.***>日期： 2022年12月2日周五 中午11:03收件人： Fantasy-Studio/Paint-by-Example ***@***.***>抄送： Subscribed ***@***.***>主    题： [Fantasy-Studio/Paint-by-Example] about environment (Issue #5)

***@***.***#egg=taming-transformers

it's a no found page

how to solve it

looking forward to your reply，thank you

**Comment by Fantasy-Studio** [comment]
Can you show the full error log?

**Comment by monument-and-sea-all-the-gift** [comment]
> Can you show the full error log?

![图片](https://user-images.githubusercontent.com/66421027/205212342-6da83d15-c7bb-45d3-a284-a13f9adc4444.png)

**Comment by Fantasy-Studio** [comment]
Maybe you can try the following script.
 "pip install -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers"

**Comment by monument-and-sea-all-the-gift** [comment]
> Maybe you can try the following script. "pip install -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers"

I Already tried and get same error

**Comment by monument-and-sea-all-the-gift** [comment]
> Maybe you can try the following script. "pip install -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers"

meybe because my ip in China，need a vpn

**Comment by Fantasy-Studio** [comment]
> 



> > Maybe you can try the following script. "pip install -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers"
> 
> meybe because my ip in China，need a vpn

Yeah, I think so. Maybe you can download the the taming transfomer repo from github to your PC. Then copy it to your server and install it locally.

**Comment by monument-and-sea-all-the-gift** [comment]
> > 
> 
> > > Maybe you can try the following script. "pip install -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers"
> > 
> > 
> > meybe because my ip in China，need a vpn
> 
> Yeah, I think so. Maybe you can download the the taming transfomer repo from github to your PC. Then copy it to your server and install it locally. https://github.com/CompVis/taming-transformers

OK,thank you
