### ISSUE TITLE
Generates Black Image

### ISSUE THREAD

**Issue by MuhammadArham-43** [Fantasy-Studio/Paint-by-Example#7]
I tried to infer on all three example images provided in the repository. It returns zero tensors and black images are saved as output. 

The output print statements highlighted possible NSFW content in the images, so I removed the checkSafety function from the inference script. However, the issue still remains and the model returns only black images.

The conda environment setup had no problems and I can find no alternate solution to the current problem. 

![grid-example_3_5065](https://user-images.githubusercontent.com/83957084/205232642-c63bf2a7-1966-4fda-a534-bf74b67f9fe5.png)
![grid-example_2_5876](https://user-images.githubusercontent.com/83957084/205232652-914e5678-65b2-48a9-bd83-fb3fd1bbd8d2.png)
![grid-example_1_321](https://user-images.githubusercontent.com/83957084/205232657-cee52a64-a537-428e-a1ea-4c61303db7d6.png)

**Comment by Fantasy-Studio** [comment]
We appreciate your interest in our work. We just tested the inference code on both the new machine and the colab, and both produce the same results as shown in the README. We will the colab code later. Thank you.

**Comment by MuhammadArham-43** [comment]
> 

The checkpoint I used previously was faulty. Currently working after I downloaded the pretrained model again. Working now.

Thank you.

**Comment by lin08288** [comment]
我遇到了同样的问题，输出是全黑的图像。我已经按要求下载了model.ckpt（11.7G）文件并放在项目的checkpoints目录下，但是还是没法解决问题，请问是为什么？
