### ISSUE TITLE
Training Config

### ISSUE THREAD

**Issue by JuewenPeng** [Fantasy-Studio/Paint-by-Example#9]
Really interesting work. 

I have one question about "v1.yaml" in "configs". I noticed that you set parameter "cond_stage_trainable" to "true". Does it mean that you also finetuned CLIP during training?

Looking forward to your reply.

**Comment by Fantasy-Studio** [comment]
We appreciate your interest in our work. We do not finetune the CLIP model. We set the parameter "cond_stage_trainable" to "true" because several MLP layers in cond_stage need to be trained and they do not belong to CLIP model.

**Comment by JuewenPeng** [comment]
Thank you very much.

**Comment by kunalgoyal9** [comment]
@Fantasy-Studio Can we use stable-diffusion model trained using dreambooth to generate results with your pipeline?
